# bag-of-word model with RandomForestClassifier

In [1]:
import pandas as pd
import numpy as np

In [2]:
d = pd.read_csv(r"C:\Users\ADITYA\Desktop\Comment Classification\Youtube Comments\Youtube01-Psy.csv") 

In [3]:
# spam:1   and   not spam:0
d.tail(10)


COMMENT_ID  \
340  z12exzcrvpeew1yxg04cd5tbwnmfubnh4kk0k   
341      z13qyxk5tzq1e5asx22xjt3wdq3ns32f5   
342  z12uyzhazxqkzbrzz04cedqpkwzdvjyy3u40k   
343  z13sh3cz1kbqgrai504cf53qsq25ypmi5zs0k   
344      z12etrpq5xu0vnm2g230szo5ote3zviny   
345      z13th1q4yzihf1bll23qxzpjeujterydj   
346  z13fcn1wfpb5e51xe04chdxakpzgchyaxzo0k   
347    z130zd5b3titudkoe04ccbeohojxuzppvbg   
348    z12he50arvrkivl5u04cctawgxzkjfsjcc4   
349  z13vhvu54u3ewpp5h04ccb4zuoardrmjlyk0k   

                                   AUTHOR                 DATE  \
340                            Anthony1SV  2014-11-14T00:01:37   
341                         Ameenk Chanel  2014-11-14T11:50:02   
342                        Brandon Wilson  2014-11-14T12:21:52   
343                      Leonel Hernandez  2014-11-14T12:35:38   
344                           InterGaming  2014-11-14T13:16:24   
345                       Carmen Racasanu  2014-11-14T13:27:52   
346                       diego mogrovejo  2014-11-14T13:28:08   
347  BlueYetiPlayz -Call Of Duty and More  2015-05-23T13:04:32   
348                          Photo Editor  2015-06-05T14:14:48   
349                            Ray Benich  2015-06-05T18:05:16   

                                               CONTENT  CLASS  
340  Please do buy these new Christmas shirts! You ...      1  
341  Free my apps get 1m crdits ! Just click on the...      1  
342  Why does a song like this have more views than...      0  
343   Something to dance to, even if your sad JUST ...      0  
344  everyones back lool this is almost 3 years old...      0  
345  How can this have 2 billion views when there's...      0  
346         I don't now why I'm watching this in 2014      0  
347  subscribe to me for call of duty vids and give...      1  
348  hi guys please my android photo editor downloa...      1  
349  The first billion viewed this because they tho...      0

In [4]:
len(d.query('CLASS==1'))      # spam

175

In [5]:
len(d.query('CLASS==0'))      # not spam

175

CountVectorizer: counts how many times each word appears and puts them into a vector

In [6]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()

In [7]:
# discovers whic words are present in dataset
dvec = vectorizer.fit_transform(d['CONTENT'])

In [8]:
# gives bag of words matrix for phrases in count
dvec

<350x1418 sparse matrix of type '<class 'numpy.int64'>'
	with 4354 stored elements in Compressed Sparse Row format>

In [9]:
print(d['CONTENT'][0])
#analyze(d['CONTENT'][0])

Huh, anyway check out this you[tube] channel: kobyoshi02


In [10]:
# to find out which word the dataset found after vectorizing
vectorizer.get_feature_names()

['00',
 '000',
 '02',
 '034',
 '05',
 '08',
 '10',
 '100',
 '100000415527985',
 '10200253113705769',
 '1030',
 '1073741828',
 '11',
 '1111',
 '112720997191206369631',
 '12',
 '123',
 '124',
 '124923004',
 '126',
 '127',
 '13017194',
 '131338190916',
 '1340488',
 '1340489',
 '1340490',
 '1340491',
 '1340492',
 '1340493',
 '1340494',
 '1340499',
 '1340500',
 '1340502',
 '1340503',
 '1340504',
 '1340517',
 '1340518',
 '1340519',
 '1340520',
 '1340521',
 '1340522',
 '1340523',
 '1340524',
 '134470083389909',
 '1415297812',
 '1495323920744243',
 '1496241863981208',
 '1496273723978022',
 '1498561870415874',
 '161620527267482',
 '171183229277',
 '19',
 '19924',
 '1firo',
 '1m',
 '20',
 '2009',
 '2012',
 '2012bitches',
 '2013',
 '2014',
 '201470069872822',
 '2015',
 '2017',
 '210',
 '23',
 '24',
 '24398',
 '243a',
 '279',
 '29',
 '2b',
 '2billion',
 '2x10',
 '300',
 '3000',
 '313327',
 '315',
 '322',
 '33',
 '33gxrf',
 '39',
 '390875584405933',
 '391725794320912',
 '40beuutvu2zkxk4utgpz8k',
 '

In [11]:
# to shufffle dataset with fraction 100%
data_shuffle = d.sample(frac=1)

In [12]:
data_shuffle.head()

COMMENT_ID  \
211  z13ccrthzkqdhl0ia04cjvobvtmafbd53ow0k   
225      z13sw1fapx2dijgv323dur5rcyz3urnut   
298    z12mubjyckfjvhmni23bc5nxbnrggtvjq04   
263    z122ybty1la4dbrz304cgnoh1knkiv0odfg   
223    z12hidxilpv4uduvf23jdjp4nleeulehc04   

                                 AUTHOR                 DATE  \
211                           Pro Video  2014-11-07T17:53:51   
225  none dies virgin life fucks us all  2014-11-07T20:05:35   
298            Bishwaroop Bhattacharjee  2014-11-08T12:34:11   
263                         bruno jovao  2014-11-08T04:51:38   
223                      Daniel Istrati  2014-11-07T19:47:16   

                                               CONTENT  CLASS  
211                               subscribe to me :)       1  
225  You think you're smart?        Headbutt your f...      0  
298  https://www.facebook.com/SchoolGeniusNITS/phot...      1  
263                                               LoL      0  
223                  Can anyone sub to my channel? :D      1

In [13]:
d_train = data_shuffle[:300]
d_test = data_shuffle[300:]
d_train_att = vectorizer.fit_transform(d_train['CONTENT'])  #fit bag of words on training set(learn the words and produce amatrix)
d_test_att = vectorizer.transform(d_test['CONTENT'])       # reuse on testing set
d_train_label = d_train['CLASS']
d_test_label = d_test['CLASS']

In [14]:
d_train_att

<300x1247 sparse matrix of type '<class 'numpy.int64'>'
	with 3630 stored elements in Compressed Sparse Row format>

In [15]:
d_test_att

<50x1247 sparse matrix of type '<class 'numpy.int64'>'
	with 543 stored elements in Compressed Sparse Row format>

Using Random Forest Classifier

In [16]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=80)   #converting dataset into 80 different trees

In [17]:
clf.fit(d_train_att, d_train_label)   #fitting trainig set

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=80,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [18]:
clf.score(d_test_att, d_test_label)   # calculating score performance on testing set

0.96

In [19]:
from sklearn.metrics import confusion_matrix
pred_labels = clf.predict(d_test_att)
confusion_matrix(d_test_label, pred_labels)

array([[29,  1],
       [ 1, 19]], dtype=int64)

In [20]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(clf,d_train_att, d_train_label, cv=5)

print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(),scores.std()*2))

Accuracy: 0.96 (+/- 0.06)


In [21]:
#loading all datasets and combining them 

d = pd.concat([pd.read_csv(r"C:\Users\ADITYA\Desktop\Comment Classification\Youtube Comments\Youtube01-Psy.csv"),
               pd.read_csv(r"C:\Users\ADITYA\Desktop\Comment Classification\Youtube Comments\Youtube02-KatyPerry.csv"),
               pd.read_csv(r"C:\Users\ADITYA\Desktop\Comment Classification\Youtube Comments\Youtube03-LMFAO.csv"),
               pd.read_csv(r"C:\Users\ADITYA\Desktop\Comment Classification\Youtube Comments\Youtube04-Eminem.csv"),
               pd.read_csv(r"C:\Users\ADITYA\Desktop\Comment Classification\Youtube Comments\Youtube05-Shakira.csv")])

In [22]:
len(d.query('CLASS==1'))   #spam

1005

In [23]:
len(d.query('CLASS==0'))    #not spam

951

In [24]:
#shuffling entire datset and separating coments and class answers
dshuff = d.sample(frac=1)
d_content = dshuff['CONTENT']
d_label = dshuff['CLASS']

'''Pipeline is really convenient and will bring together two or more steps so that all the steps are 
treated as one. So, we will build a pipeline with the bag of words, and then use countVectorizer
followed by the random forest classifier. Then we will print the pipeline.
'''

In [25]:
#set up a pipeline
from sklearn.pipeline import Pipeline, make_pipeline
pipeline = Pipeline([
    ('bag-of-words',CountVectorizer()),
    ('random forest',RandomForestClassifier()),
])
pipeline

Pipeline(memory=None,
         steps=[('bag-of-words',
                 CountVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.int64'>, encoding='utf-8',
                                 input='content', lowercase=True, max_df=1.0,
                                 max_features=None, min_df=1,
                                 ngram_range=(1, 1), preprocessor=None,
                                 stop_words=None, strip_accents=None,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, vocabu...
                 RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                        class_weight=None, criterion='gini',
                                        max_depth=None, max_features='auto',
                                        max_leaf_nodes=None, max_samples=None,
                                

In [26]:
# say combining CountVectorizer and RandomForestClassifer() into one
make_pipeline(CountVectorizer(),RandomForestClassifier())

Pipeline(memory=None,
         steps=[('countvectorizer',
                 CountVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.int64'>, encoding='utf-8',
                                 input='content', lowercase=True, max_df=1.0,
                                 max_features=None, min_df=1,
                                 ngram_range=(1, 1), preprocessor=None,
                                 stop_words=None, strip_accents=None,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, voc...
                 RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                        class_weight=None, criterion='gini',
                                        max_depth=None, max_features='auto',
                                        max_leaf_nodes=None, max_samples=None,
                                

In [27]:
#first perform fit then transform with CountVectorizer followed by fit of randomForest classifier
pipeline.fit(d_content[:1500],d_label[:1500])

Pipeline(memory=None,
         steps=[('bag-of-words',
                 CountVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.int64'>, encoding='utf-8',
                                 input='content', lowercase=True, max_df=1.0,
                                 max_features=None, min_df=1,
                                 ngram_range=(1, 1), preprocessor=None,
                                 stop_words=None, strip_accents=None,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, vocabu...
                 RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                        class_weight=None, criterion='gini',
                                        max_depth=None, max_features='auto',
                                        max_leaf_nodes=None, max_samples=None,
                                

In [28]:
pipeline.score(d_content[1500:], d_label[1500:])

0.9649122807017544

In [29]:
pipeline.predict(["What a project Aditya!"])

array([0], dtype=int64)

In [30]:
pipeline.predict(["Please vit guys subscribe to my youtube channel"])

array([1], dtype=int64)

In [34]:
pipeline.predict(["have a look to my channel"])

array([1], dtype=int64)

In [31]:
#cross validation
scores = cross_val_score(pipeline, d_content, d_label,cv=5)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std()* 2))

Accuracy: 0.96 (+/- 0.02)


In [32]:
# can add TD-IDF(Term Frequency Inverse Document Frequecy) to make it more precise:
# TD-IDF measures how commmon a word or term is in the document
# can also apply the parameter search feature known as grid search.

# word2vec, doc2vec are better models than bag-of-words model